const Product = [
    {
        id: 1,
        title: 'Samsung Galaxy Z Flip4',
        description:
            'Samsung Galaxy Z Flip4 128GB đã chính thức ra mắt thị trường công nghệ, đánh dấu sự trở lại của Samsung trên con đường định hướng người dùng về sự tiện lợi trên những chiếc điện thoại gập. Với độ bền được gia tăng cùng kiểu thiết kế đẹp mắt giúp Flip4 trở thành một trong những tâm điểm sáng giá cho nửa cuối năm 2022. ',
        price: 20.990,
        image: '1.jpg',
        evaluate: 853,
        capacity1: '64GB',
        capacity2: '256GB',
        capacity3: '512GB',
        special: 's1.png',
        camera1: '6.7" & Phụ 1.9"',
        camera2: 'FULL HD+',
        category: 'Phone',
        rating: 4.5,
        qnty:1,
        system: 'Android',
    },
    {
        id: 2,
        title: 'IPhone 11',
        description:
            'Apple đã chính thức trình làng bộ 3 siêu phẩm iPhone 11, trong đó phiên bản iPhone 11 64GB có mức giá rẻ nhất nhưng vẫn được nâng cấp mạnh mẽ như iPhone Xr ra mắt trước đó.',
        price: 11.790,
        image: '2.jpg',
        evaluate: 1000,
        special: 's5.png',
        capacity1: '64GB',
        capacity2: '128GB',
        camera1: 'Chính 6.1',
        camera2: 'Liquid Retina',
        category: 'Phone',
        rating: 2.5,
        qnty:1,
        system: 'Apple',
    },
    {
        id: 3,
        title: 'Xiaomi Redmi Note 11',
        description:
            'Điện thoại Redmi được mệnh danh là dòng sản phẩm quốc dân ngon - bổ  - rẻ của Xiaomi và Redmi Note 11 (4GB/64GB) cũng không phải ngoại lệ, máy sở hữu một hiệu năng ổn định, màn hình 90 Hz mượt mà, cụm camera AI đến 50 MP cùng một mức giá vô cùng tốt.',
        price: 4.490,
        image: '3.jpeg',
        evaluate: 452,
        special: 's3.png',
        capacity1: '5GB',
        capacity2: '4GB-128GB',
        capacity3: '6GB-128GB',
        camera1: 'Chính 6.43',
        camera2: 'FULL HD+',
        category: 'Phone',
        rating: 3.0,
        qnty:1,
        system: 'Android',
    },
    {
        id: 4,
        title: 'Samsung Galaxy S22 Ultra',
        description:
            'Galaxy S22 Ultra 5G chiếc smartphone cao cấp nhất trong bộ 3 Galaxy S22 series mà Samsung đã cho ra mắt. Tích hợp bút S Pen hoàn hảo trong thân máy, trang bị vi xử lý mạnh mẽ cho các tác vụ sử dụng vô cùng mượt mà và nổi bật hơn với cụm camera không viền độc đáo mang đậm dấu ấn riêng.',
        price: 25.990,
        image: '4.jpg',
        evaluate: 761,
        special: 's1.png',
        capacity1: '64GB',
        capacity2: '12GB-256GB',
        capacity3: '12GB-512GB',
        camera1: 'Chính 6.8',
        camera2: 'Quad HD+ (2K+)',
        category: 'Phone',
        rating: 4.0,
        qnty:1,
        system: 'Android',
    },
    {
        id: 5,
        title: 'Xiaomi Redmi Note 11S',
        description:
            'Điện thoại Redmi Note 11S 5G có ngoại hình bắt mắt với 3 màu sắc thời thượng gồm: Trắng, xám, xanh dương. Viền màn hình hai bên của máy khá mỏng cùng với đó là cạnh viền bo cong theo lòng bàn tay, tạo cảm giác cầm nắm thoải mái hơn.',
        price: 6.490,
        image: '5.jpg',
        evaluate: 602,
        special: 's3.png',
        capacity1: '5GB',
        capacity2: '64GB',
        camera1: 'Chính 6.6',
        camera2: 'FULL HD+',
        category: 'Phone',
        rating: 2.5,
        qnty:1,
        system: 'Android',
    },
    {
        id: 6,
        title: 'IPhone 13 Pro Max',
        description:
            'Điện thoại iPhone 13 Pro Max 128 GB - siêu phẩm được mong chờ nhất ở nửa cuối năm 2021 đến từ Apple. Máy có thiết kế không mấy đột phá khi so với người tiền nhiệm, bên trong đây vẫn là một sản phẩm có màn hình siêu đẹp, tần số quét được nâng cấp lên 120 Hz mượt mà, cảm biến camera có kích thước lớn hơn, cùng hiệu năng mạnh mẽ với sức mạnh đến từ Apple A15 Bionic, sẵn sàng cùng bạn chinh phục mọi thử thách.',
        price: 28.290,
        image: '6.jpg',
        evaluate: 1000,
        special: 's1.png',
        capacity1: '64GB',
        capacity2: '256GB',
        capacity3: '512GB',
        capacity4: '1TB',
        camera1: 'Chính 6.7',
        camera2: 'Super Retina XD',
        category: 'Phone',
        rating: 4.0,
        qnty:1,
        system: 'Apple',
    },
    {
        id: 7,
        title: 'Vivo Y15s',
        description:
            'Vivo vừa mang một chiến binh mới đến phân khúc tầm trung giá rẻ có tên Vivo Y15s, một sản phẩm sở hữu khá nhiều ưu điểm như thiết kế đẹp, màn hình lớn, camera kép, pin cực trâu và còn rất nhiều điều thú vị khác đang chờ đón bạn.',
        price: 3.190,
        image: '7.jpg',
        evaluate: 203,
        special: 's3.png',
        capacity1: '5GB',
        capacity2: '16GB',
        camera1: 'Chính 6.51',
        camera2: 'HD+',
        category: 'Phone',
        rating: 3.5,
        qnty:1,
        system: 'Android',
    },
    {
        id: 8,
        title: 'OPPO A55',
        description:
            'OPPO cho ra mắt OPPO A55 4G chiếc smartphone giá rẻ tầm trung có thiết kế đẹp mắt, cấu hình khá ổn, cụm camera chất lượng và dung lượng pin ấn tượng, mang đến một lựa chọn trải nghiệm thú vị vừa túi tiền cho người tiêu dùng.',
        price: 4.190,
        special: 's5.png',
        image: '8.jpg',
        capacity1: '5GB',
        capacity2: '16GB',
        evaluate: 339,
        camera1: 'Chính 6.5',
        camera2: 'HD+',
        category: 'Phone',
        rating: 3.0,
        qnty:1,
        system: 'Android',
    },
    {
        id: 9,
        title: 'iPhone 14 Pro Max',
        description:
            'Cuối cùng thì chiếc iPhone 14 Pro Max cũng đã chính thức lộ diện tại sự kiện ra mắt thường niên vào ngày 08/09 đến từ nhà Apple, kết thúc bao lời đồn đoán bằng một bộ thông số cực kỳ ấn tượng cùng vẻ ngoài đẹp mắt sang trọng. Từ ngày 14/10/2022 người dùng đã có thể mua sắm các sản phẩm iPhone 14 series với đầy đủ phiên bản tại Thế Giới Di Động.',
        price: 33.590,
        image: '9.jpg',
        special: 's4.png',
        evaluate: 2,
        capacity1: '64GB',
        capacity2: '256BG',
        capacity3: '512GB',
        camera1: 'Chính 6.7',
        camera2: 'Super Retina XDR',
        category: 'Phone',
        rating: 4.5,
        qnty:1,
        system: 'Apple',
    },
    {
        id: 10,
        title: 'OPPO A55',
        description:
            'OPPO cho ra mắt OPPO A55 4G chiếc smartphone giá rẻ tầm trung có thiết kế đẹp mắt, cấu hình khá ổn, cụm camera chất lượng và dung lượng pin ấn tượng, mang đến một lựa chọn trải nghiệm thú vị vừa túi tiền cho người tiêu dùng.',
        price: 4.190,
        image: '10.jpg',
        evaluate: 2,
        capacity1: '5GB',
        special: 's3.png',
        capacity2: '256BG',
        capacity3: '512GB',
        camera1: 'Chính 6.7',
        camera2: 'Super Retina XDR',
        category: 'Phone',
        rating: 2.5,
        qnty:1,
        system: 'Android',
    },
    {
        id: 11,
        title: 'Asus TUF Gaming FX506LHB i5',
        description:
            'Nếu bạn đang tìm kiếm một chiếc laptop gaming nhưng vẫn sở hữu một mức giá phải chăng thì laptop Asus TUF Gaming FX506LHB i5 (HN188W) sẽ là sự lựa chọn đáng cân nhắc với card đồ họa rời NVIDIA GeForce GTX mạnh mẽ cùng phong cách thiết kế cứng cáp, độc đáo. ',
        price: 18.190,
        image: '11.jpeg',
        special: 's2.png',
        evaluate: 59,
        capacity1: 'Ram 8GB',
        capacity2: 'SSD 512GB',
        camera1: 'Chính 15.6',
        camera2: 'Full HD, 144Hz',
        category: 'Laptop',
        rating: 4.5,
        qnty:1,
        system: 'Gaming',
    },
    {
        id: 12,
        title: 'Aspire 7 Gaming A715',
        description:
            'Laptop Aspire 7 Gaming A715 42G R4XX R5 (NH.QAYSV.008) sở hữu hiệu năng khoẻ cùng thiết kế mạnh mẽ, là bạn đồng hành lý tưởng trong mọi cuộc hành trình.',
        price: 14.490,
        image: '12.jpg',
        special: 's4.png',
        evaluate: 72,
        capacity1: 'Ram 8GB',
        capacity2: 'SSD 512GB',
        camera1: 'Chính 15.6',
        camera2: 'Full HD',
        category: 'Laptop',
        rating: 4.5,
        qnty:1,
        system: 'Gaming',
    },
    {
        id: 13,
        title: ' Lenovo Ideapad Gaming 3 15IAH7 i5',
        description:
            'Laptop Lenovo Ideapad Gaming 3 15IAH7 i5 (82S9007TVN) thuộc dòng laptop gaming mang vẻ đẹp ấn tượng, cuốn hút nhưng không kém phần mạnh mẽ nhờ vào CPU Intel Gen 12, sẵn sàng đồng hành cùng bạn trên mọi đấu trường game hiện nay.',
        price: 26.190,
        image: '13.jpg',
        special: 's6.jpg',
        evaluate: 3,
        capacity1: 'Ram 8GB',
        capacity2: 'SSD 512GB',
        camera1: 'Chính 15.6',
        camera2: 'Full HD,120HZ',
        category: 'Laptop',
        rating: 4.5,
        qnty:1,
        system: 'Gaming',
    },
    {
        id: 14,
        title: 'Dell Gaming G15 5515 R5',
        description:
            'Bộ hiệu năng gây ấn tượng đến từ con chip AMD mạnh mẽ cùng thiết kế cá tính, nổi bật, laptop Dell Gaming G15 5515 R5 (P105F004DGR) sẽ đáp ứng tối ưu mọi nhu cầu từ các tác vụ văn phòng cơ bản đến những ứng dụng đồ họa, chơi game giải trí chuyên nghiệp.',
        price: 23.490,
        image: '14.jpg',
        special: 's7.png',
        evaluate: 15,
        capacity1: 'Ram 16GB',
        capacity2: 'SSD 512GB',
        camera1: 'Chính 15.6',
        camera2: 'Full HD,120HZ',
        category: 'Laptop',
        rating: 4.5,
        qnty:1,
        system: 'Gaming',
    },
    {
        id: 15,
        title: 'Apple MacBook Air M1',
        description:
            'Laptop Apple MacBook Air M1 2020 thuộc dòng laptop cao cấp sang trọng có cấu hình mạnh mẽ, chinh phục được các tính năng văn phòng lẫn đồ hoạ mà bạn mong muốn, thời lượng pin dài, thiết kế mỏng nhẹ sẽ đáp ứng tốt các nhu cầu làm việc của bạn.',
        price: 24.690,
        image: '15.jpg',
        special: 's5.png',
        evaluate: 78,
        capacity1: 'Ram 8GB',
        capacity2: 'SSD 256GB',
        camera1: 'Chính 15.6',
        camera2: 'Retina',
        category: 'Laptop',
        rating: 4.5,
        qnty:1,
        system: 'Macbook',
    },
    {
        id: 16,
        title: 'Apple MacBook Air M1',
        description:
            'Laptop Apple MacBook Air M1 2020 thuộc dòng laptop cao cấp sang trọng có cấu hình mạnh mẽ, chinh phục được các tính năng văn phòng lẫn đồ hoạ mà bạn mong muốn, thời lượng pin dài, thiết kế mỏng nhẹ sẽ đáp ứng tốt các nhu cầu làm việc của bạn.',
        price: 41.990,
        image: '16.jpg',
        special: 's5.png',
        evaluate: 1,
        capacity1: 'Ram 8GB',
        capacity2: 'SSD 256GB',
        camera1: 'Chính 15.6',
        camera2: 'Retina',
        category: 'Laptop',
        rating: 4.5,
        qnty:1,
        system: 'Macbook',
    },
    {
        id: 17,
        title: 'MacBook Pro 14 M1 Pro',
        description:
            'Khoác lên mình vẻ ngoài mới lạ so với các dòng Mac trước đó, thiết kế màn hình tai thỏ ấn tượng, bắt mắt cùng bộ hiệu năng đỉnh cao M1 Pro mạnh mẽ, MacBook Pro 14 inch M1 Pro 2021 xứng tầm là chiếc laptop cao cấp chuyên dụng dành cho dân kỹ thuật - đồ họa, sáng tạo nội dung.',
        price: 63.050,
        image: '17.jpg',
        special: 's5.png',
        evaluate: 1,
        capacity1: 'Ram 8GB',
        capacity2: 'SSD 512GB',
        camera1: 'Chính 14.2',
        camera2: 'Retina,120Hz',
        category: 'Laptop',
        rating: 5,
        qnty:1,
        system: 'Macbook',
    },
    {
        id: 18,
        title: 'Lenovo Tab M8',
        description:
            'Lenovo Tab M8 chiếc máy tính bảng giá rẻ, cấu hình ổn, thiết kế cao cấp trong tầm giá, hoàn toàn phù hợp với các nhu cầu cơ bản như đọc báo, xem phim, lướt web hằng ngày.',
        price: 3.690,
        image: '18.jpg',
        special: 's8.png',
        evaluate: 47,
        capacity1: '5GB',
        capacity2: '16GB',
        camera1: 'IPS LCD',
        camera2: 'Phụ 8.0',
        category: 'Tablet',
        rating: 4.0,
        qnty: 1,
        system: 'Android',
    },
    {
        id: 19,
        title: 'Nokia Tab T20 4G',
        description:
            'Máy tính bảng Nokia đánh dấu sự trở lại của hãng trên thị trường tablet sau nhiều năm vắng bóng bằng việc ra mắt Nokia Tab T20 máy có thiết kế kim loại sang trọng, hiệu năng ổn định cùng màn hình hiển thị sắc nét, mang đến một lựa chọn không thể bỏ qua trong phân khúc.',
        price: 4.990,
        image: '19.jpeg',
        special: 's5.png',
        evaluate: 39,
        capacity1: '5GB',
        capacity2: '16GB',
        camera1: 'IPS LCD',
        camera2: 'Phụ 10.4',
        category: 'Tablet',
        rating: 4.0,
        qnty:1,
        system: 'Android',
    },
    {
        id: 20,
        title: 'iPad Pro M2 12.9 inch',
        description:
            'Apple đang ngày càng bỏ xa nhiều đối thủ về mặt hiệu năng trên các dòng tablet, điều này được minh chứng cụ thể bằng sự xuất hiện của con chip Apple M2 siêu mạnh mẽ trên iPad Pro M2 12.9 inch WiFi Cellular 128GB. Bên cạnh đó thì máy còn có những nâng cấp như hệ điều hành iPadOS 16, viên pin 40.88 Wh.',
        price: 35.990,
        image: '20.jpg',
        special: 's2.png',
        evaluate: '',
        capacity1: '128GB',
        capacity2: '256GB',
        camera1: 'Liquid Retina XDR',
        camera2: '12.9',
        category: 'Tablet',
        rating: 5.0,
        qnty:1,
        system: 'Apple',
    },
    {
        id: 21,
        title: 'Huawei MatePad 11',
        description:
            'MatePad 11 - chiếc máy tính bảng Huawei với lối thiết kế tối giản nhưng vẫn toát lên vẻ sang trọng, sở hữu trong mình cấu hình mạnh mẽ, màn hình lớn cùng một viên pin trâu có thể đáp ứng được hầu hết các tác vụ làm việc, học tập hay giải trí.',
        price: 12.790,
        image: '22.jpg',
        special: 's1.png',
        evaluate: 2,
        capacity1: '64GB',
        capacity2: '256GB',
        camera1: 'IPS LCD',
        camera2: '10.9',
        category: 'Tablet',
        rating: 5.0,
        qnty:1,
        system: 'Android',
    },
    
]
export default Product;

